### ISSUE TITLE
Incompatiblity between falcon hooks and webargs (falcon >= 1.4.0)

### ISSUE THREAD

**Issue by ignacioHermosilla** [marshmallow-code/webargs#217] opened 2018-04-27 15:50 UTC
**Falcon 1.4** changed the implementation of hooks and now this is non-compatible with **Webargs**, here a sample that works only with Falcon < 1.4.0.

```
import falcon
from webargs import fields
from webargs.falconparser import use_args

def fake_validator(req, resp, resource, params):
    pass

class BlogResource(object):
    request_args = {
        'title': fields.Str(required=True)
    }

    @falcon.before(fake_validator)
    @use_args({'title': fields.Str(required=True)})
    def on_post(self, req, resp, args, post_id):
        content = args['title']
        resp.media = {'content': content}

api = application = falcon.API()
api.add_route('/blogs/{post_id}', BlogResource())
```

My environment:

falcon==1.4.1
webargs==2.1.0
Python 2.7.11

**Comment by sloria** [comment] 2018-05-04 02:13
Thanks for reporting! I would certainly review and merge a PR fixing this.

**Comment by sloria** [comment] 2018-12-28 21:22
I am not able to reproduce this issue with falcon==1.4.1 and the latest webargs release. Closing for now, but feel free to comment if this is still an issue.

**Closed as completed by sloria** 2018-12-28 21:22 UTC
Labels: help wanted
