### ISSUE TITLE
webargs.async and webargs.aiohttpparser contain un-guarded Python 3 syntax

### ISSUE THREAD

**Issue by ijstokes** [marshmallow-code/webargs#105] opened 2016-05-02 15:29 UTC
`pip install webargs` or `setuptools`-based install `python setup.py install` of `webargs` when using Python 2.x results in `SyntaxError` on either of these statements:

```
import webargs.async
import webargs.aiohttpparser
```

Perhaps it makes sense to incorporate an import guard that would raise an `ImportError` instead, or something that would more clearly indicate that those sub-modules aren't available when using Python 2.x

Incidentally, I came across this while trying to create conda packages for `webargs` that work with Python 2.7.

**Comment by freddrake** [comment] 2016-05-02 16:40
Isn't this the same as issue #86?

Ultimately, the problem is that tools attempt to force byte-compilation without considering syntax errors being reported during parsing (not execution).  There's nothing that can be done about this from within the code of the offending modules, aside from avoiding Python 3 syntax completely.  I'm not sure there's a valid reason for that in the case of these particular modules.

Ultimately, byte-compilation steps from tools should tolerate these syntax errors and simply not install generated .pyc files for modules that trigger these errors.

**Comment by freddrake** [comment] 2016-05-02 16:44
Alternately, these modules could be dropped from installations targeting Python 2.

Making the tools (setuptools, pip, the Debian install process) more resilient is probably the better approach, because it applies to all packages, rather than forcing all affected packages to worry about this. But this can be reasonably argued either way.

**Comment by sloria** [comment] 2016-05-29 23:12
There doesn't seem to be a clean way to do this in `setup.py`, though I may be missing something.

One alternative would be to separate the aiohttp code into a separate package. It's really not ideal though, because that would be a breaking change.

**Comment by asmodehn** [comment] 2016-11-14 08:59
I am having this problem as well, trying to release webargs for [ROS](http://www.ros.org/)
Not really breaking, since I don't use aiohttp or any async behavior though. The `.pyc` files are just missing from the final deb package.

IMHO, using FromWrapper() from trollius for now (not a breaking change I believe) is probably best option... How about it ?

And _maybe_ at some point in the future, separate "all async" behavior requiring python3, in a different subpackage/plugin ? I m kind of expecting more async driven python3 webservers will appear...

**Comment by sloria** [comment] 2017-03-16 00:44
Closing this for now, since we don't have plans on making changes to support this.

**Closed as completed by sloria** 2017-03-16 00:44 UTC
