### ISSUE TITLE
split parse and validate into 2 phases!

### ISSUE THREAD

**Issue by pingf** [marshmallow-code/webargs#152] opened 2017-02-10 02:48 UTC
I have written an api framework based on falcon, however, within it, the framework already parse the params. which makes using webargs a little bit ugly.

heres the [demo](https://github.com/pingf/falsy/blob/master/demo/webargs/ops/hello.py) for my frame work [falsy](https://github.com/pingf/falsy)

because I already parse the req into function param name, so, is there any way to use the webargs field validation directly?

**Comment by sloria** [comment] 2017-02-10 03:37
webargs uses marshmallow for validation/deserialization, so I suppose you could use marshmallow directly for validation. Would that meet your use case?

**Comment by pingf** [comment] 2017-02-10 03:59
yeah, because our project is based on flask, and now want to change to our own framework.
we used webargs in our project, which defines schema in json. we do not want to recode the validation part. just check the source of this project and find the correct part may help. 

thx a lot.

```python
def argmap2schema(argmap, instance=False, **kwargs):
    """Generate a `marshmallow.Schema` class given a dictionary of argument
    names to `Fields <marshmallow.fields.Field>`.
    """
    class Meta(object):
        strict = True
    attrs = dict(argmap, Meta=Meta)
    cls = type(str(''), (ma.Schema,), attrs)
    return cls if not instance else cls(**kwargs)
```

**Comment by sloria** [comment] 2017-02-13 14:32
I'm not sure I understand the problem completely, but validation is done almost exclusively by marshmallow, so could you use `marshmallow.Schema#validate` to validate the request data?

**Comment by hnjttsocssac** [comment] 2017-02-14 01:46
yeah, thx, the problem is solved by using the argmap2schema func.
because our old project is using webargs, we define the schema with json style

```
{
   'name': fields.Str(validate=lambda p: len(p) >= 6, required=True),
}
```

however, we are moving to our own framework, if we change to marshmallow directly, we need to change to the schema style(we need to define the schema class), which force us to rewrite hundreds of dicts.

the thing behind this is that our framework parses the params directly, the controller is something like this, 
```
def get_it(name):
    return {
        'get': name
    }
```
the name can be something in query, path or header etc.

however, the decorator doesn't work for this situitation, for it doesn't expose the req object.

so, if there's a decorator can be used with the function params(not the req object) directly, it will solve the problem.

currently, I just use the argmap2schema function and marshmallow directly to make things work.

**Comment by pingf** [comment] 2017-02-14 01:47
yeah, thx, the problem is solved by using the argmap2schema func.
because our old project is using webargs, we define the schema with json style
```json
{
   'name': fields.Str(validate=lambda p: len(p) >= 6, required=True),
}
```
however, we are moving to our own framework, if we change to marshmallow directly, we need to change to the schema style(we need to define the schema class), which force us to rewrite hundreds of dicts.

the thing behind this is that our framework parses the params directly, the controller is something like this,
```python
def get_it(name):
    return {
        'get': name
    }
```
the name can be something in query, path or header etc.

however, the decorator doesn't work for this situitation, for it doesn't expose the req object.

so, if there's a decorator can be used with the function params(not the req object) directly, it will solve the problem.

currently, I just use the argmap2schema function and marshmallow directly to make things work.

**Comment by sloria** [comment] 2017-02-14 03:00
You should be able to write a decorator to validate the input arguments for your controllers.

How about something along the lines of:

```python
def validate(argmap):
    schema = argmap2schema(argmap, instance=True)
    def decorator(func):
        @functools.wraps(func)
        def decorated(*args, **kwargs):
            schema.validate(kwargs)
            return func(*args, **kwargs)
        return decorated
    return decorator
```

You would use it like:

```python
from marshmallow import fields

@validate({
    'x': fields.Int(),
    'y': fields.Int(),
})
def add(x, y):
    return x + y

add(x='invalid', y=2)  # ValidationError: {'x': ['Not a valid integer.']}
```

**Comment by pingf** [comment] 2017-02-14 03:11
wow, this is real black magic, thx a lot~

**Closed as completed** 2017-02-14 14:30 UTC

**Comment by pingf** [comment] 2017-02-15 02:26
sorry for bother you again, the argmap2schema may have some problems, see the code below, 
the required check is neglected, however, it has some relations with the strict attr in the meta class.
```python
import functools

from marshmallow import fields
from webargs import argmap2schema

from marshmallow import Schema
def argmap2schema(argmap, instance=False, **kwargs):
    class Meta(object):
        strict = True
    attrs = dict(argmap, Meta=Meta)
    cls = type(str(''), (Schema,), attrs)
    return cls if not instance else cls(**kwargs)

def validate(argmap):
    schema = argmap2schema(argmap, instance=True)
    def decorator(func):
        @functools.wraps(func)
        def decorated(*args, **kwargs):
            print(kwargs)
            schema.validate(kwargs)
            return func(*args, **kwargs)
        return decorated
    return decorator

@validate({
    's': fields.Str(required=False),
})
def add(s):
    print(s)
    return s

add(s=None)
```
