### ISSUE TITLE
Importing webargs causing issue on Python 3.7.0

### ISSUE THREAD

**Issue by karunvarma** [marshmallow-code/webargs#578] opened 2021-01-03 11:29 UTC
Traceback (most recent call last):
  File "C:\dev\Learning\api\flaskapisepc\app.py", line 1, in <module>
    from webargs import fields
  File "C:\dev\Learning\api\flaskapisepc\venv\lib\site-packages\webargs\__init__.py", line 7, in <module>
    from webargs.core import ValidationError
  File "C:\dev\Learning\api\flaskapisepc\venv\lib\site-packages\webargs\core.py", line 33, in <module>
    ErrorHandler = typing.Callable[..., typing.NoReturn]
  File "C:\Users\kd185138\AppData\Local\Programs\Python\Python37\lib\typing.py", line 755, in __getitem__
    return self.__getitem_inner__(params)
  File "C:\Users\kd185138\AppData\Local\Programs\Python\Python37\lib\typing.py", line 251, in inner
    return func(*args, **kwds)
  File "C:\Users\kd185138\AppData\Local\Programs\Python\Python37\lib\typing.py", line 774, in __getitem_inner__
    result = _type_check(result, msg)
  File "C:\Users\kd185138\AppData\Local\Programs\Python\Python37\lib\typing.py", line 135, in _type_check
    raise TypeError(f"Plain {arg} is not valid as type argument")
TypeError: Plain typing.NoReturn is not valid as type argument

**Comment by lafrech** [comment] 2021-01-03 11:47
Duplicate of #573.

**Closed as completed by lafrech** 2021-01-03 11:47 UTC
