### ISSUE TITLE
Strange warning from PyCharm: Unexpected type(s): (Dict[str, String]) Possible type(s): (Union[SchemaABC, type, str, () -> SchemaABC]) (Union[SchemaABC, type, str, () -> SchemaABC])

### ISSUE THREAD

**Issue by sarimmehdi** [marshmallow-code/webargs#671] opened 2021-12-26 22:29 UTC
I get this warning in PyCharm when using webargs to create a nested dictionary object:

```
data_args = {
    "name": fields.Nested(
        {"first": fields.Str(required=True), "last": fields.Str(required=True)}
    )
}
```

It happens for this line:

`{"first": fields.Str(required=True), "last": fields.Str(required=True)}`

Code is taken from the official [webargs](https://webargs.readthedocs.io/en/latest/quickstart.html#nesting-fields) tutorial:

Why is PyCharm warning me about this and what should be the correct course of action?

**Comment by sirosen** [comment] 2022-01-03 15:07
I believe that what's happening here is that PyCharm is seeing `fields.Nested` as referring to `marshmallow.fields.Nested`. Webargs provides its own subclass which supports dict instantiation, `webargs.fields.Nested`.

Could you share your import lines? It's possible that PyCharm is flagging a real error here. I'm also going to file a related issue to discuss a potential mitigation for this source of confusion.

**Comment by sarimmehdi** [comment] 2022-01-03 18:20
@sirosen my import line is the same as in the tutorial: `from webargs import fields`

**Comment by sirosen** [comment] 2022-01-03 18:37
That's interesting. I can explain the cause, but I'll have to experiment a little when I have time to find a resolution.

The error message from PyCharm is related to type annotations and type information. `webargs.fields.Nested` inherits from `marshmallow.fields.Nested`. The `marshmallow` field has a type annotation on `__init__` but the `webargs` one does not. I believe that the type checker thinks that the type of `__init__` is the same, but it is not. Specifically, `webargs.fields.Nested` accepts a `Dict[str, marshmallow.fields.Field]`, whereas the original `Nested` does not.

This kind of subclassing should be allowed by my understanding. I think we just need to type annotate `webargs.fields.Nested.__init__` and all will be well.

For the very short term, a `# type: ignore` comment on the offending line would probably squash the warning. But I'll make it a priority to sort this out after my workday.

**Comment by sirosen** [comment] 2022-01-04 16:55
Unfortunately, even if we annotate the signature for `Nested` in `webargs`, it doesn't satisfy type checkers. They still understand `Nested` to have the type of the original class.

I'm putting together a PR which will rename `Nested` to `WebargsNested`. If it gets merged, it will update the example in the docs and solve this problem.

**Comment by sirosen** [comment] 2022-03-15 20:45
In the past few days, `marshmallow` has done a release which should resolve this issue. You will need to ensure that pycharm (or any other type checker) is using the latest `marshmallow` version.

We also may have cleanup to do in `webargs`, but it should not impact users.

**Closed as completed by sirosen** 2022-03-15 20:45 UTC

**Comment by lafrech** [comment] 2022-03-15 20:50
Yeah, we should remove `Nested` here but this requires bumping minimum marshmallow version, so I suppose it'll wait until next major webargs version.
