### ISSUE TITLE
Missing form field falls back to json by default, which throws 400 error

### ISSUE THREAD

**Issue by Deimos** [marshmallow-code/webargs#444] opened 2019-12-07 22:32 UTC
I'm working on trying to update my Pyramid application to webargs > 5.0, which is requiring a lot of changes. I've just run into an unexpected error with one of my forms, where I don't think webargs' default behavior is correct. It's somewhat similar to closed issue #409, but I wasn't specifying `locations` like they were, and just using the default behavior.

Specifically, my view is for a POST endpoint, and has a decorator like this on it (along with a second one that uses a schema for the other data):

    @use_kwargs({"confirm": Boolean(missing=False)})

The form doesn't always contain the `confirm` input (it's for a special case), so my expectation is that when they submit the form without any data for `confirm`, it should get set to `False`.

However, because of this part of webargs' default behavior ([from here](https://webargs.readthedocs.io/en/latest/quickstart.html#request-locations)):

> By default, webargs will search for arguments from the URL query string (e.g. `"/?name=foo"`), form data, and JSON data (in that order).

What actually happens is that it fails to find `confirm` in the form data, so it tries to look for it in JSON, and then throws a 400 error (`pyramid.httpexceptions.HTTPBadRequest: {'json': ['Invalid JSON body.']}`) because there is no JSON on the request.

It works as expected if I specify `locations=("form",)` in `@use_kwargs`, but having the default behavior cause a crash by falling back to looking for nonexistent JSON data doesn't seem right. Should the lack of JSON data be treated as "no data" instead of an error?

Edit: wanted to also note that I'm upgrading from 4.4.1, and this worked fine in that version without crashing.

**Comment by lafrech** [comment] 2019-12-08 14:14
This should be fixed (more precisely obsoleted) by #420.

**Comment by lafrech** [comment] 2020-02-14 21:21
Closing this now that #420 was merged.

You can try the latest 6.0.0 beta releases to confirm that the issue is fixed.

If not, please comment here and we'll reopen.

**Closed as completed by lafrech** 2020-02-14 21:21 UTC
